name: LibsDisguises
main: me.libraryaddict.disguise.LibsDisguises
description: A disguise plugin with various disguises.
version: ${project.version}
author: libraryaddict
authors: [Byteflux, Navid K.]
depend: [ProtocolLib]
permissions:
    libsdisguises.reload:
        description: Allows the user to reload LibsDisguises.
        default: op
    libsdisguises.seethrough:
        description: Allows player to see through disguises.
        default: false
